- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Setup Variables
      include_vars: vars/vpc_setup
      
    - name: Create vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true 
        dns_hostnames: true 
        state: "{{state}}"
        tenancy: default
        tags:
          Environment: "Production"
          Project: "VprProject" 
      register: vpcout  

    - debug: 
        var: vpcout 

    - name: Create Public subnet1 in  Zone1
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub1Cidr}}"
        az: "{{zone1}}"
        map_public: yes
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out  

    - debug: 
        var: pubsub1_out 

 