---
- name: Install and Set up RabbitMQ with user
  hosts: rmqsrvgrp
  # from ansible.cfg
  gather_facts: no
 
  tasks:
    - name: Copy over the installaton shell script from files/rabbitmq-shell-install-script.sh
      copy:
        src: files/rabbitmq-shell-install-script.sh
        dest: /home/ubuntu
        mode: 0777
 
 
    - name: execute the shell installation script
      # the entire script can be found here https://www.rabbitmq.com/docs/install-debian
      #script: /home/ubuntu/rabbitmq-shell-install-script.sh
      command: sh /home/ubuntu/rabbitmq-shell-install-script.sh
 
 
 
    - name: Start and enable RMQ service
      service: 
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc
 
    
    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
        # put the content above into the dest config file above
      notify:
        - Restart RMQ
      tags:
        - conf
 
 
    - name: Configure the rabbitmq username and password
      rabbitmq_user:
      # https://docs.ansible.com/ansible/latest/collections/community/rabbitmq/rabbitmq_user_module.html
        user: test
        password: test
        # see the provision-stack/templates/application.j2 file. rabbitmq.username=test and rabbitmq.password=test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf
 
 
    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package
 
 
  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
          
